export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";
export const NEW_CATEGORY_FIELD_UPDATE = "NEW_CATEGORY_FIELD_UPDATE";
export const CATEGORY_FETCHED = "CATEGORY_FETCHED";
export const CLEAR_CATEGORY_FIELDS = "CLEAR_CATEGORY_FIELDS";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const CLEAR_SELECTED_CATEGORY = "CLEAR_SELECTED_CATEGORY";
export const HANDLE_DELETE_MODAL_STATUS = "HANDLE_DELETE_MODAL_STATUS";